### ISSUE TITLE
Object can't be rotated

### ISSUE THREAD

**Issue by danielmee** [ozgrozer/hdt#3]
Obviously more a feature request than a bug but being able to rotate the object would make it more likely that the scene in mind can be created and also better match the object together (ie necks come out at the right angle).

**Comment by ozgrozer** [comment]
I couldn't find any React rotate library at the moment. If I find one I'd like to add that feature.

**Comment by CITGuru** [comment]
https://www.npmjs.com/package/react-rotation
https://www.npmjs.com/package/react-rotate

These can help with these

**Comment by ozgrozer** [comment]
Yeah that would be cool. I can't find any time to improve it anymore.

**Comment by CITGuru** [comment]
https://www.npmjs.com/package/react-rnd-rotate and I just found this. I am working on it now

**Comment by CITGuru** [comment]
@ozgrozer I have been able to fix this and also add lots of improvement and redesign

**Comment by ozgrozer** [comment]
@CITGuru Sounds great. Is there any working example that we can see?

**Comment by CITGuru** [comment]
rockitool.herokuapp.com @ozgrozer. So many bugs though, but still working on it in my free time

**Comment by CITGuru** [comment]
And using pure html and css for this sounds cool but it still limited and html2canvas is limited too

**Comment by ozgrozer** [comment]
This is going to be a cool app.

**Comment by CITGuru** [comment]
Sure. So what do you thin about this

**Comment by srihariash999** [comment]
@CITGuru  Hi man, so, download option in your website is not working. Is that not implemented ?

**Comment by ozgrozer** [comment]
> @CITGuru Hi man, so, download option in your website is not working. Is that not implemented ?

You can save the images by clicking "SAVE JPG" and "SAVE PNG" buttons.

**Comment by srihariash999** [comment]
@ozgrozer  sorry, I was talking about the @CITGuru 's heroku app. Can't find where to contact him about it, so i asked here. Sorry
