### ISSUE TITLE
Move to Back/Front doesn't work after the first time

### ISSUE THREAD

**Issue by simonpeterdebbarma** [ozgrozer/hdt#4]
I've been unable to move assets to the front/back of other assets. It works only once on a single asset after I clear the entire worksheet, and then fails to work on any other assets.

Workaround: Put the assets you want at the back first.

**Comment by ozgrozer** [comment]
The way it works, it uses CSS z-index property and it doesn't go below `z-index: 1;`. I made this in a rush so that was the first thing that came to my mind 😅 So if you want to move something back, then first you should move the other object front.
